name : Java8 CICD with Actions

# 触发条件， 当指定分支 push 代码时触发
on: 
  push:
    branches:
      - develop
      
# 环境变量
env:
  IMAGE_NAME: allentest
  APP_JAR_DIR: target/allentest-0.0.1-SNAPSHOT.jar
  
# 任务列表， 测试步骤暂时空缺
jobs:
  # 自动化单元测试
  test:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "测试成功"
      
# maven 编译打包， 和 Dockerfile 制作镜像， push 到 dockerhub 仓库
  compile-build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: |-
          mvn package -U -Dcodegen.skip -Dmaven.test.skip=true
          mv $APP_JAR_DIR app.jar
          docker build -f Dockerfile -t $IMAGE_NAME .
      - uses: elgohr/Publish-Docker-Github-Action@master
        with: 
          name: ${{ secrets.DOCCKER_USERNAME}}/${{ secrets.DOCKER_REGISTRY}}
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
          tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
        
  
  deploy:
    needs: compile-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: garygrossgarten/github-action-scp@release
        with: 
          local: deploy.sh
          remote: deploy.sh
          host: ${{ secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USER}}
          password: ${{ secrets.SERVER_PASS}}
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USER}}
          password: ${{ secrets.SERVER_PASS}}
          port: 22
          script: |-
            chmod +x deploy.sh
            sh deploy.sh
            rm -rf deploy.sh
